### DISCUSSION TITLE
Release a Docker container?

### DISCUSSION THREAD

**Discussion by Jerrk** [JohnDoee/autotorrent2#39] [Q&A]
I'm using unraid and have been using a userscript combined with the NerdPack plugin to run at2.

In 6.11.x Nerdpack is no longer working due to the author going MIA, and since its not recommended to install packages system-wide in the first place, making a (official?) docker container seems like a good idea.

Thing is i am completely out of my depth and i have no idea how to dockerize at2, and i was hoping someone else would be able to assist.

at2 will surely reach a larger user base with an official docker container as well if that is something to be considered.

**Comment by DoAndroids** [comment]
I know this is an old post, but for when others come looking, here's a docker-compose setup example that makes it easy to include

Firstly you need to clone the repo:
`git clone https://github.com/JohnDoee/autotorrent2.git`

Then the docker-compose.yml file (in the directory above 'autotorrent2'):
```
version: '3.9'
services:
 vpn:
  image: (your vpn image)
 network_mode: "bridge"
 environment:
  (all the vpn settings etc.)

 autotorrent2:
  build:
    context: ./autotorrent2
    dockerfile: Dockerfile
  network_mode: "service:vpn"
  container_name: autotorrent2
  environment:
   - PUID=${PUID}
   - PGID=${PGID}
   - TZ=${TZ}
  tmpfs:
   - /tmp
  volumes:
   - ./config:/config
   - ./config:/app/autotorrent/.config
  command: scan-clients; at2 scan; at2 find-unseeded
```

This assumes you have a .env file that has the PUID / PGID / TZ settings in.
